name: CI with different Java versions

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '11', '17']
    name: Java ${{ matrix.java }} System-Lambda
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup java
      uses: actions/setup-java@v3
      with: 
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
#    - name: Build and Test
#      run: scripts/test.sh
